name: Run CFcdnym Script

on:
  push:
    branches:
      - main  # 或者你希望触发的其他分支

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download and run CFcdnym.sh
        run: |
          curl -sSL https://gitlab.com/rwkgyg/CFwarp/raw/main/point/CFcdnym.sh -o CFcdnym.sh
          chmod +x CFcdnym.sh
          bash CFcdnym.sh
